### ISSUE TITLE
Artefact not available from maven central

### ISSUE THREAD

**Issue by andipabst** [webjars/datatables-responsive#1]
The artefact is listed in the maven search https://search.maven.org/artifact/org.webjars/datatables-responsive/2.2.3/jar and also listed at https://repo1.maven.org/maven2/org/webjars/datatables-responsive/2.2.3/, but clicking the link to the jar there gives an error 404.

Also this webjar is not available via webjars.org.

**Comment by andipabst** [comment]
@jamesward  could you please have a look at this? Maybe it simply needs to be released again.

**Comment by jamesward** [comment]
It seems to be working for me.  Maybe it was syncing still?  Or maybe you have a firewall or something blocking jar downloads?

**Comment by andipabst** [comment]
Strange, now it works well. Sorry for bothering you and thanks for having a look!
